/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Filme;
import model.Usuario;
import services.FilmeServicos;
import services.ServicosFactory;
import services.UsuarioServicos;

/**
 *
 * @author sarin
 */
public class jfFilme extends javax.swing.JFrame {

    /**
     * Creates new form jfFilme
     */
    public jfFilme() {
        initComponents();
        addRowToTable();
        this.setLocationRelativeTo(null);
    }

    public boolean validaInputs() {
        if (jtfTitulo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher título!");
            jtfTitulo.requestFocus();
            return false;
        } else if (jtfAnoLancamento.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher ano de lançamento!");
            jtfAnoLancamento.requestFocus();
            return false;
        } else if (jtfAtores.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher atores!");
            jtfAtores.requestFocus();
            return false;
        } else if (jtfNacionalidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher nacionalidade!");
            jtfNacionalidade.requestFocus();
            return false;
        } else if (jtfGenero.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher gênero!");
            jtfGenero.requestFocus();
            return false;
        } else if (jtfDuracaoTempo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher duração do tempo!");
            jtfDuracaoTempo.requestFocus();
            return false;
        } else if (jtfEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher e-mail!");
            jtfEmail.requestFocus();
            return false;
        }
        return true;
    }//fim validaInputs

    private void addRowToTable() {
        DefaultTableModel model = (DefaultTableModel) jtFilmes.getModel();
        model.getDataVector().removeAllElements();//Remove todas as linhas.
        model.fireTableDataChanged();
        Object rowData[] = new Object[7];//rowData é o vetor para popular a linha da tabela por coluna
        FilmeServicos filmeS = ServicosFactory.getFilmeServicos();
        for (Filme s : filmeS.buscaFilmes()) {//O vetor sempre começa em 0
            rowData[0] = s.getTitulo();
            rowData[1] = s.getAnoLancamento();
            rowData[2] = s.getNomeAtor();
            rowData[3] = s.getNacionalidade();
            rowData[4] = s.getGenero();
            rowData[5] = s.getDuracaoEspera();
            rowData[6] = s.getIdUsuario().getNomeUsuario();
            model.addRow(rowData);//Add para popular.
        }
    }

    public void somenteNum(java.awt.event.KeyEvent evt) {
        String number = "0123456789";
        if (jtfAnoLancamento.getText().length() < 13) {
            if (!number.contains(evt.getKeyChar() + "")) {//evento(evt) a tecla que foi teclada.
                evt.consume();
            }
        } else {
            evt.consume();
        }
    }

    public void somenteLetrasAcentos(java.awt.event.KeyEvent evt) {
        String nletras = "0123456789<>:?/}][{=+-_!|'\'@#$%¨&*()²³£¢¬§º°ª";
        if (nletras.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFilmes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfTitulo = new javax.swing.JTextField();
        jtfAnoLancamento = new javax.swing.JTextField();
        jtfAtores = new javax.swing.JTextField();
        jtfNacionalidade = new javax.swing.JTextField();
        jtfGenero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfDuracaoTempo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerência Filme");

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jPanel3.setBackground(new java.awt.Color(0, 204, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerência Filme");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtFilmes.setBackground(new java.awt.Color(255, 255, 255));
        jtFilmes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título", "Ano de Lançamento", "Atores", "Nacionalidade", "Gênero", "Duração de Tempo", "Usuário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFilmesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFilmes);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Título:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ano de Lançamento:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nacionalidade(s):");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Atores:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gênero:");

        jtfTitulo.setBackground(new java.awt.Color(0, 153, 153));
        jtfTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jtfTitulo.setToolTipText("Informe o título da série");
        jtfTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfTitulo.setCaretColor(new java.awt.Color(0, 0, 0));

        jtfAnoLancamento.setBackground(new java.awt.Color(0, 153, 153));
        jtfAnoLancamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfAnoLancamento.setForeground(new java.awt.Color(0, 0, 0));
        jtfAnoLancamento.setToolTipText("Informe o ano de lançamento da série");
        jtfAnoLancamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfAnoLancamento.setCaretColor(new java.awt.Color(0, 0, 0));
        jtfAnoLancamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAnoLancamentoKeyTyped(evt);
            }
        });

        jtfAtores.setBackground(new java.awt.Color(0, 153, 153));
        jtfAtores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfAtores.setForeground(new java.awt.Color(0, 0, 0));
        jtfAtores.setToolTipText("Informe o elenco da série");
        jtfAtores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfAtores.setCaretColor(new java.awt.Color(0, 0, 0));
        jtfAtores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAtoresKeyTyped(evt);
            }
        });

        jtfNacionalidade.setBackground(new java.awt.Color(0, 153, 153));
        jtfNacionalidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNacionalidade.setForeground(new java.awt.Color(0, 0, 0));
        jtfNacionalidade.setToolTipText("Informe a(s) nacionalidade(s) dos atores");
        jtfNacionalidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfNacionalidade.setCaretColor(new java.awt.Color(0, 0, 0));
        jtfNacionalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNacionalidadeKeyTyped(evt);
            }
        });

        jtfGenero.setBackground(new java.awt.Color(0, 153, 153));
        jtfGenero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfGenero.setForeground(new java.awt.Color(0, 0, 0));
        jtfGenero.setToolTipText("Informe o gênero da série");
        jtfGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfGenero.setCaretColor(new java.awt.Color(0, 0, 0));
        jtfGenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfGeneroKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Duração de Tempo:");

        jtfDuracaoTempo.setBackground(new java.awt.Color(0, 153, 153));
        jtfDuracaoTempo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfDuracaoTempo.setForeground(new java.awt.Color(0, 0, 0));
        jtfDuracaoTempo.setToolTipText("Informe o tempo que parou no filme");
        jtfDuracaoTempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfDuracaoTempo.setCaretColor(new java.awt.Color(0, 0, 0));
        jtfDuracaoTempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDuracaoTempoKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Usuário:");

        jtfEmail.setBackground(new java.awt.Color(0, 153, 153));
        jtfEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfEmail.setForeground(new java.awt.Color(0, 0, 0));
        jtfEmail.setToolTipText("Informe seu e-mail");
        jtfEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfEmail.setCaretColor(new java.awt.Color(0, 0, 0));
        jtfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEmailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jtfTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDuracaoTempo)
                            .addComponent(jtfAtores)
                            .addComponent(jtfNacionalidade)
                            .addComponent(jtfGenero)
                            .addComponent(jtfAnoLancamento)
                            .addComponent(jtfEmail))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfAnoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfAtores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDuracaoTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtFilmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFilmesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFilmesMouseClicked

    private void jtfAnoLancamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAnoLancamentoKeyTyped
        // TODO add your handling code here:
        somenteNum(evt);
    }//GEN-LAST:event_jtfAnoLancamentoKeyTyped

    private void jtfAtoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAtoresKeyTyped
        // TODO add your handling code here:
        somenteLetrasAcentos(evt);
    }//GEN-LAST:event_jtfAtoresKeyTyped

    private void jtfNacionalidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNacionalidadeKeyTyped
        // TODO add your handling code here:
        somenteLetrasAcentos(evt);
    }//GEN-LAST:event_jtfNacionalidadeKeyTyped

    private void jtfGeneroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfGeneroKeyTyped
        // TODO add your handling code here:
        somenteLetrasAcentos(evt);
    }//GEN-LAST:event_jtfGeneroKeyTyped

    private void jtfDuracaoTempoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDuracaoTempoKeyTyped
        // TODO add your handling code here:
        somenteNum(evt);
    }//GEN-LAST:event_jtfDuracaoTempoKeyTyped

    private void jtfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEmailFocusLost
        // TODO add your handling code here:
        UsuarioServicos usuS = ServicosFactory.getUsuarioServicos();
        Usuario usu = usuS.buscarUsuariobyEmail(jtfEmail.getText());
        if (usu.getEmail() == null) {
            JOptionPane.showMessageDialog(this, "Usuário não cadastrado!", "Pesquisa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Object[] resp = {"Sim", "Não"};
            int resposta = JOptionPane.showOptionDialog(this, "Usuario " + usu.getNomeUsuario() + " está correto? ", "Pesquisa", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, resp, resp[0]);
            if (resposta == 1) {
                jtfEmail.setText("");
                jtfEmail.requestFocus();
            }
        }
    }//GEN-LAST:event_jtfEmailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtFilmes;
    private javax.swing.JTextField jtfAnoLancamento;
    private javax.swing.JTextField jtfAtores;
    private javax.swing.JTextField jtfDuracaoTempo;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfGenero;
    private javax.swing.JTextField jtfNacionalidade;
    private javax.swing.JTextField jtfTitulo;
    // End of variables declaration//GEN-END:variables
}
