/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexao.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sarin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);//Para centralizar a janela
    }

    public boolean validaInputs() {
        if (jtfEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher e-mail!");
            jtfEmail.requestFocus();
            return false;
        } else if (new String(jpfSenha.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher senha!");
            jpfSenha.requestFocus();
            return false;
        }
        return true;
    }//fim validaInputs

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jlEsqueciSenha = new javax.swing.JLabel();
        jbCriarConta = new javax.swing.JButton();
        jbEntrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acesso");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 100, 40));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-mail");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 70, -1));

        jtfEmail.setBackground(new java.awt.Color(0, 0, 0));
        jtfEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfEmail.setForeground(new java.awt.Color(255, 255, 255));
        jtfEmail.setToolTipText("Informa e-mail cadastrado ");
        jtfEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jtfEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 231, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 231, 10));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 60, -1));

        jpfSenha.setBackground(new java.awt.Color(0, 0, 0));
        jpfSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpfSenha.setForeground(new java.awt.Color(255, 255, 255));
        jpfSenha.setToolTipText("Informe senha cadastrada");
        jpfSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpfSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(jpfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 231, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 231, 10));

        jlEsqueciSenha.setFont(new java.awt.Font("Monotype Corsiva", 1, 20)); // NOI18N
        jlEsqueciSenha.setForeground(new java.awt.Color(19, 196, 19));
        jlEsqueciSenha.setText("Esqueceu a senha?");
        jlEsqueciSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlEsqueciSenhaMouseClicked(evt);
            }
        });
        jPanel1.add(jlEsqueciSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 140, -1));

        jbCriarConta.setBackground(new java.awt.Color(0, 0, 204));
        jbCriarConta.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jbCriarConta.setForeground(new java.awt.Color(255, 255, 255));
        jbCriarConta.setText("Criar Conta");
        jbCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarContaActionPerformed(evt);
            }
        });
        jPanel1.add(jbCriarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        jbEntrar.setBackground(new java.awt.Color(0, 0, 204));
        jbEntrar.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jbEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jbEntrar.setText("Entrar");
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-login96.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/capa login.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 430, 480));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Organizador ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("De");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 60, -1));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Séries e Filmes");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarActionPerformed
        // TODO add your handling code here:
        // O ? é subtituído pelo conteúdo das variáveis(email e senha). 

        try {
            Connection con = Conexao.getConexao();
            //As linhas abaixo preparam a consulta ao banco em função do que foi digitado nas caixas de texto.
            String sql = "select * from usuarios where email = ? and senha = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, jtfEmail.getText());
            pst.setString(2, new String(jpfSenha.getPassword()));
            //A linha abaixo executa a query, vai fazer a pesquisa no BD.
            ResultSet rs = pst.executeQuery();
            //Se existir usuário e senha correspondente.
            if (rs.next()) {
                //Chama a tela 
                MenuPrincipal menuP = new MenuPrincipal();
                menuP.setVisible(true);
                menuP.logado(jtfEmail.getText());
                setVisible(false);//Para esconder a tela de Login

                JOptionPane.showMessageDialog(this, "Seja Bem-Vindo");
            } else {
                JOptionPane.showMessageDialog(this, "Email ou senha incorretos.");
            }
        } catch (SQLException ex) {//Caso ocorra alguma exceção.
            ex.printStackTrace();//Variável ex vai exibir a mensagem de erro.
        }
    }//GEN-LAST:event_jbEntrarActionPerformed

    private void jbCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarContaActionPerformed
        // TODO add your handling code here:
        TelaCadastro telaCad = new TelaCadastro();
        telaCad.setVisible(true);
    }//GEN-LAST:event_jbCriarContaActionPerformed

    private void jlEsqueciSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEsqueciSenhaMouseClicked
        // TODO add your handling code here:
        RecuperacaoSenha recSenha = new RecuperacaoSenha();
        recSenha.setVisible(true);
    }//GEN-LAST:event_jlEsqueciSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbCriarConta;
    private javax.swing.JButton jbEntrar;
    private javax.swing.JLabel jlEsqueciSenha;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfEmail;
    // End of variables declaration//GEN-END:variables
}
