/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;

/**
 *
 * @author sarin
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);//Para centralizar a janela
    }
    
    public static String emailLogado = null;

    public void logado(String email) {//Método criado para só o email de tal usuário vai ter acesso as séries e filmes cadastrados, como também o usuário vai ter acesso só a seu email cadastrado.
        emailLogado = email;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiSerie = new javax.swing.JMenuItem();
        jmiFilme = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiUsuario = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenu();
        jmiFechar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/capaMenuPrincipal.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 50, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(140, 107, 140));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gerenciamento.png"))); // NOI18N
        jMenu1.setText("Gerenciamento");
        jMenu1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N

        jmiSerie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiSerie.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmiSerie.setForeground(new java.awt.Color(0, 0, 0));
        jmiSerie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/serie.png"))); // NOI18N
        jmiSerie.setMnemonic('S');
        jmiSerie.setText("Série");
        jmiSerie.setToolTipText("Cadastrar, Editar, Atualizar e Remover.");
        jmiSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSerieActionPerformed(evt);
            }
        });
        jMenu1.add(jmiSerie);

        jmiFilme.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiFilme.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmiFilme.setForeground(new java.awt.Color(0, 0, 0));
        jmiFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/film.png"))); // NOI18N
        jmiFilme.setMnemonic('F');
        jmiFilme.setText("Filme");
        jmiFilme.setToolTipText("Cadastrar, Editar, Atualizar e Remover.");
        jmiFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFilmeActionPerformed(evt);
            }
        });
        jMenu1.add(jmiFilme);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/configuracao.png"))); // NOI18N
        jMenu2.setText("Configuração");
        jMenu2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N

        jmiUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiUsuario.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmiUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jmiUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/vcard.png"))); // NOI18N
        jmiUsuario.setMnemonic('U');
        jmiUsuario.setText("Usuário");
        jmiUsuario.setToolTipText("Editar, Atualizar e Remover.");
        jmiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jmiUsuario);

        jMenuBar1.add(jMenu2);

        jmiSair.setForeground(new java.awt.Color(0, 0, 0));
        jmiSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sair.png"))); // NOI18N
        jmiSair.setText("Sair");
        jmiSair.setToolTipText("Fecha a janela");
        jmiSair.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N

        jmiFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiFechar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmiFechar.setForeground(new java.awt.Color(0, 0, 0));
        jmiFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fechar.png"))); // NOI18N
        jmiFechar.setMnemonic('F');
        jmiFechar.setText("Fechar");
        jmiFechar.setToolTipText("Fechar Organizador");
        jmiFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFecharActionPerformed(evt);
            }
        });
        jmiSair.add(jmiFechar);

        jMenuBar1.add(jmiSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuarioActionPerformed
        // TODO add your handling code here:
        jfUsuario janelaUsuario = new jfUsuario();
        janelaUsuario.setVisible(true);
    }//GEN-LAST:event_jmiUsuarioActionPerformed

    private void jmiSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSerieActionPerformed
        // TODO add your handling code here:
        jfSerie janelaSerie = new jfSerie();
        janelaSerie.setVisible(true);
    }//GEN-LAST:event_jmiSerieActionPerformed

    private void jmiFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFilmeActionPerformed
        // TODO add your handling code here:
        jfFilme janelaFilme = new jfFilme();
        janelaFilme.setVisible(true);
    }//GEN-LAST:event_jmiFilmeActionPerformed

    private void jmiFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFecharActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jmiFecharActionPerformed

    public void close() {
        WindowEvent closeEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeEvent);
        System.exit(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmiFechar;
    private javax.swing.JMenuItem jmiFilme;
    private javax.swing.JMenu jmiSair;
    private javax.swing.JMenuItem jmiSerie;
    private javax.swing.JMenuItem jmiUsuario;
    // End of variables declaration//GEN-END:variables
}
